### ISSUE TITLE
Enable this plugin to work with all known file types (ex: Kotlin sources)

### ISSUE THREAD

**Issue by Suseika** [minman/altn8#17]
Would be nice to have.

**Comment by minman** [comment]
Ok, thank you for reporting. For the moment just add "ks" and "kts" to Other Settings > AltN8 > File Extension.

**Comment by minman** [comment]
I'm thinking about to remove the "File Extension" settings and automatically support all file types recognized by IDEA (https://www.jetbrains.com/idea/help/file-types.html). So if someone has for example the kotlin plugin active, automatically kotlin files are supported. What do you think about this approach?

**Comment by Suseika** [comment]
I think it would be great.
